### ISSUE TITLE
Bug: You aren't initializing the month/year/day that you're passing into the DatePicker

### ISSUE THREAD

**Issue by KyleBastien** [mviencek/Assignment_1#2]
https://github.com/mviencek/Assignment_1/blob/ffa6ea877b24056c326aae247ea95271ce874107/app/src/main/java/com/example/mvien/assignment_1/MainActivity.java#L61

So you're passing null null null, and it's going to achieve weird behavior, which I can see in your app in that it's hard to manipulate the date the first time around. You should initialize these fields in your onCreate.

**Comment by mviencek** [comment]
initialized when its created

**Comment by mviencek** [comment]
will commit the code fix later tonight
