### ISSUE TITLE
Bug: Screen rotation happens asynchronously 

### ISSUE THREAD

**Issue by KyleBastien** [mviencek/Assignment_1#4]
https://github.com/mviencek/Assignment_1/blob/ffa6ea877b24056c326aae247ea95271ce874107/app/src/androidTest/java/com/example/mvien/assignment_1/main_activity_test.java#L58

Therefore you need to wait until it's done to keep executing your test. See my InClassDemo repo, in my TestUtils class.

**Comment by mviencek** [comment]
i will fix this for the next assignment

**Comment by mviencek** [comment]
fixed
