### ISSUE TITLE
Flaky Test: This will have after some time passes

### ISSUE THREAD

**Issue by KyleBastien** [mviencek/Assignment_1#5]
https://github.com/mviencek/Assignment_1/blob/ffa6ea877b24056c326aae247ea95271ce874107/app/src/androidTest/java/com/example/mvien/assignment_1/main_activity_test.java#L146

For example, next year, when this person is 19, your test will fail because of the hardcoded birthday. You'll have to calculate their right age, or have a dynamic birthday.

**Comment by mviencek** [comment]
ill fix this for the next time around

**Comment by mviencek** [comment]
fixed
